// Platform definitions with constraints
export const PLATFORMS = {
  twitter: {
    id: 'twitter',
    name: 'Twitter/X',
    icon: '𝕏',
    maxCharacters: 280,
    supportsImages: true,
    supportsVideos: true,
    supportsLinks: true,
    hashtagRules: 'Max 10 hashtags',
    color: '#1DA1F2',
  },
  instagram: {
    id: 'instagram',
    name: 'Instagram',
    icon: '📷',
    maxCharacters: 2200,
    supportsImages: true,
    supportsVideos: true,
    supportsLinks: false,
    hashtagRules: 'Max 30 hashtags, place in first comment',
    color: '#E4405F',
  },
  facebook: {
    id: 'facebook',
    name: 'Facebook',
    icon: 'f',
    maxCharacters: 63206,
    supportsImages: true,
    supportsVideos: true,
    supportsLinks: true,
    hashtagRules: 'Use 1-2 hashtags',
    color: '#1877F2',
  },
  linkedin: {
    id: 'linkedin',
    name: 'LinkedIn',
    icon: 'in',
    maxCharacters: 3000,
    supportsImages: true,
    supportsVideos: true,
    supportsLinks: true,
    hashtagRules: 'Max 5 hashtags recommended',
    color: '#0A66C2',
  },
  tiktok: {
    id: 'tiktok',
    name: 'TikTok',
    icon: '♪',
    maxCharacters: 150,
    supportsImages: false,
    supportsVideos: true,
    supportsLinks: false,
    hashtagRules: 'Max 3-5 hashtags',
    color: '#000000',
  },
};

export const PLATFORM_LIST = Object.values(PLATFORMS);
